[program:uniorthocrin-onedrive-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/codestackrg/Projects/UniOrthocrin/uniorthocrin/artisan queue:work database --timeout=600 --tries=3 --memory=512 --sleep=3 --verbose
directory=/home/codestackrg/Projects/UniOrthocrin/uniorthocrin
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/home/codestackrg/Projects/UniOrthocrin/uniorthocrin/storage/logs/worker.log
stopwaitsecs=3600
